---
title: "Dietary preprocessing"
format: html
editor: visual
---

```{r}
library(openxlsx)
```


# Food groups merging and consolidating

```{r}
df <- read.xlsx("../../../data/raw/food_groups/VG_ITEMS_24.07_MERGED_CLEANED_CORRECT_FOODGROUPS_ONLY.xlsx")
```

ABOUT PDI https://pmc.ncbi.nlm.nih.gov/articles/PMC10257227/#bib15
https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1002039

```{r}
apply(df,2,function(x) length(unique(x)))
```

```{r}
writeLines(unique(df$foodgroup),"../../../docs/info_foodgroups/foodgroups.txt")
writeLines(unique(df$MAINgroup),"../../../docs/info_foodgroups/maingroups.txt")
writeLines(unique(df$PDIgroup),"../../../docs/info_foodgroups/pdigroups.txt")
```

NAs in PDI

```{r}
pdi_na <- df %>% dplyr::filter(is.na(PDIgroup))

unique(pdi_na$MAINgroup)  
unique(pdi_na$foodgroup)  
```

```{r}
library(dplyr)
```

# FG MERGED MEAN

```{r}
dietary_df <- read.table("../../../Docs/fg_merged_mean.tsv",header=TRUE)
```

```{r}
dietary_df <- dietary_df %>%
  `rownames<-`(dietary_df$client) %>%
  dplyr::select(-client) 
```

## Imputation

No need for imputation

```{r}
dietary_df[dietary_df==""] <- NA

sum(is.na(dietary_df))
```

```{r}
pdf("../../Results/preprocessing/dietary_density_plots.pdf",width = 10,height = 5)
plot_density(dietary_df)
dev.off()
```

## Normalization

We have to normalize the information according to the calories.

```{r}
dietary_df[,4:111] <- apply(dietary_df[,4:111],2,function(x) x/dietary_df[,3])
```

```{r}
pdf("../../Results/preprocessing/dietary_density_plots_norm.pdf",width = 10,height = 5)
plot_density(dietary_df)
dev.off()
```

## Log-transformation

Log-transformation and visualizing density plot.

```{r}
data_clean_log <- as.data.frame(
  apply(dietary_df,2,function(x) as.numeric(x)))
data_clean_log <- log(data_clean_log)
rownames(data_clean_log) <- rownames(dietary_df)

# LETS deal with -Inf -> -10
data_clean_log[data_clean_log==-Inf] <- -10
```

```{r}
pdf("../../Results/preprocessing/dietary_density_plots_log.pdf",width = 10,height = 5)
plot_density(data_clean_log)
dev.off()
```

## Autoscaling

```{r}
data_scaled <- data_clean_log
data_scaled <- scale(data_scaled, center = TRUE, scale = TRUE)

```

```{r}
pdf("../../Results/preprocessing/dietary_density_plots_scaled.pdf",width = 10,height = 5)
plot_density(data_scaled)
dev.off()
```

```{r}
filtered_df <- data_scaled[, colMeans(is.na(data_scaled)) < 0.5]
```

```{r}
write.table(filtered_df,"../../../Data/preprocessed/dietary/fg_merged_mean_preprocessed.tsv",row.names = TRUE,sep="\t")
```

# FG MERGED FULL

```{r}
dietary_df <- read.table("../../../Docs/fg_merged_MAINGROUPS_full_mean.tsv",header=TRUE)
```

```{r}
dietary_df$MAIN.group[dietary_df$MAIN.group==""] <- "unknown"
```

```{r}
clients <- 
```
